-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbALMksKuD1lRZZR/
iX/aqpXOID1CjZDzFZd26R/D+OmgCgYIKoZIzj0DAQehRANCAASSEbCl4qv3LwRP
ENvxzdo0Y4q3/2x/Zmk4YtDMCgvZrbJnuHESRvuS5GcXyfw0R4ptehs8+dsM3iVm
cMO3Rymk
-----END PRIVATE KEY-----