name: globcare

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.26+106

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



    #------- payment--------------
  urwaypayment:
    git: https://github.com/SmartMind4sys/urway-payment.git



  slide_countdown:
    git: https://github.com/waleedalmadhab/slide_countdown.git

  animated_custom_dropdown:
    git: https://github.com/waleedalmadhab/custom-dropdown.git

#  open_file:
#    git: https://github.com/waleedalmadhab/open_file.git

  #---------------------  FireBase
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.2
  dart_jsonwebtoken: ^2.14.0
  googleapis_auth: ^1.6.0

  #  firebase_core: 2.7.1
#  firebase_messaging: 14.2.6
#  firebase_core_platform_interface: ^5.1.0
#  firebase_core: 2.15.1
#  firebase_messaging: 14.6.7
#  firebase_analytics: 10.4.5
#  firebase_core_platform_interface: 5.0.0
  #---------------------
  flutter_local_notifications: ^16.3.2

  #---------------------
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.1
  geolocator: ^12.0.0
#  google_maps_place_picker_mb: ^2.0.0-mb.22

  #---------------------


  #---------------------
  cached_network_image: ^3.3.1
  image_picker: ^0.8.5+3
  image_picker_widget: ^2.1.3
  flutter_native_image_v2: ^1.1.2+4
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.5.0
  dotted_line: ^3.2.2


  #---------------------
  device_info_plus: ^11.3.0

  #---------------------
  #---------------------
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  reactive_forms: ^16.0.4
  #---------------------
#  auto_direction: ^0.0.6
#  auto_size_text: ^3.0.0
  readmore: ^2.2.0
  #---------------------


  #---------------------
  #  carousel_slider: ^4.0.0

  circular_profile_avatar: ^2.0.5
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  rounded_loading_button_plus: ^3.0.1
  percent_indicator: ^4.2.3

  #---------------------
  animate_do: ^3.0.2
  lottie: ^2.6.0
  toggle_switch: ^2.1.0
  flutter_toggle_tab: ^1.4.1
  transitioner: ^0.1.0
  bottom_bar_page_transition: ^2.0.0
  water_drop_nav_bar: ^2.2.0+5
  flutter_staggered_animations: ^1.1.1
  flutter_animator: ^3.2.2
  smooth_page_indicator: ^1.1.0
#  flutter_animated_dialog: ^2.0.1
  showcaseview: ^3.0.0
  group_button: ^5.3.2


  #---------------------
  connectivity_plus: ^6.0.3
  dio: ^5.5.0+1
  #---------------------
  #google_maps_place_picker: ^1.0.1
  #geoflutterfire: ^3.0.1
  #---------------------
  flutter_screenutil: ^5.9.3
  #---------------------
  get: ^4.6.6
  #  get_it: ^7.2.0
  #  hive: ^2.0.4
  #  hive_flutter: ^1.1.0
  logger: ^2.3.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.10.0
  #  syncfusion_flutter_datepicker: ^19.3.48


  url_launcher: ^6.1.12
#  syncfusion_flutter_pdfviewer: ^26.1.39

  #  pedometer: ^3.0.0
  #  jiffy: ^4.1.0
  http: ^1.2.1
  #  syncfusion_flutter_gauges: ^19.3.48
  ##  scrollable_positioned_list: ^0.2.2
  #  scroll_to_index: ^2.1.0
  #  cool_dropdown: ^1.4.0

  #  introduction_screen: ^2.1.0
  #  flutter_overboard: ^3.0.0
  #device_preview: ^0.8.0
  just_audio: ^0.9.28
  record: ^3.0.2

  #  multi_select_flutter: ^4.0.0
  #  flutter_multi_select_items: ^0.1.1
  flutter_multi_formatter: ^2.7.4
  country_code_picker: ^2.0.2

  http_parser: ^4.0.1
  #date_picker_timeline: ^1.2.3
  #  calendar_agenda: ^0.0.2+3
  #  flutter_calendar_week: ^2.0.0
  #shadowed_image: ^1.0.3
  dotted_border: ^2.0.0+3
  #  container_tab_indicator: ^0.3.0
  expandable: ^5.0.1
  getwidget: ^6.0.0

  #  animated_bottom_navigation_bar: ^0.3.2
  #  circular_reveal_animation: ^2.0.0
  #  flutter_linkify: ^5.0.2
#  jitsi_meet: ^4.0.0
#  jitsi_meet_wrapper: ^0.0.5
  webview_flutter: ^4.8.0
  webview_flutter_wkwebview: ^3.14.0
  jitsi_meet_flutter_sdk: ^10.2.0
  #flutter_swiper: ^1.1.6

  get_storage: ^2.1.1
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.3
#  open_file: ^3.2.1
#  open_file_plus: ^3.3.
#  open_filex: ^3.3.2

#  file_picker_plus: ^1.3.0
#  file_picker: ^4.6.1
  open_file_plus: ^3.4.1+1
  file_picker: ^10.3.2






  #  slide_countdown: ^0.2.4
  pin_code_fields: ^8.0.1
  #  update_available: ^2.1.0
  string_mask: ^1.0.0
#  qr_code_scanner: ^0.7.0
  coupon_uikit: ^0.2.1
  #  version_check: ^0.2.1
  slide_to_confirm: ^1.1.0
  swipe: ^0.0.1
  mobile_scanner: ^5.2.0
  flutter_holo_date_picker: ^1.1.3
  package_info_plus: ^8.0.0
#  new_version_plus: ^0.0.11

  #  flutter_app_minimizer: ^0.0.2
  flutter_rating_bar: ^4.0.1
#  google_place_picker: ^1.0.2
  dialog_loader: ^0.0.3+3
  im_animations: ^0.1.2
  wakelock_plus: ^1.2.5

  collection: ^1.16.0

  group_list_view: ^1.1.1
  motion_toast: ^2.10.0
  toastification: ^2.1.0



  carousel_slider: ^4.2.1






#  native_updater: ^0.1.1
#  path_provider_extention: ^1.0.3
#  flutter_rounded_date_picker: ^2.0.2
#  syncfusion_flutter_gauges: ^19.4.55
#  flutter_fadein: ^2.0.0
#  crypto: ^3.0.1
#  convert: ^3.0.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_only.png"

#
#dependency_overrides:
#  #http: ^0.13.3
#  google_maps_flutter: ^2.0.10
#  plugin_platform_interface: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash/
    - assets/images/
    - assets/svg/
    - assets/svg/vital/
    - assets/intro/
    - assets/home_icons/
    - assets/anim/
    - assets/audios/
    - flags/
    - assets/appconfig.json
    - assets/paypallogo.png


  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf









#--no-tree-shake-icons
  #.\gradlew signingReport
